### ISSUE TITLE
Milestone - AUG 5

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#242]
@shaunanoordin @simoneduca @rogerhutchings @eatyourgreens 

I wanted to update the milestone brain dump to discrete priorities that are critical for launching the Lab publicly. Some of these are big, some are small, but I'd like to try and get these done by Aug 5, so we can test before HHMI announces the lab publicly on August 15.

THere's tons of exciting things to do afterwards, but we need to get these bits done first.

MAP EXPLORER
- [x] Add filters for: time of day (day, night, dawn, dusk); distance to human structure, distance to water source. **TOP-PRIORITY.**
- [x] see #245 Clean up CSV outputs: make column headers intuitive. Bridget will provide headers.
- [x] see #247 add layers for water, human stuff, etc.  (bridget resending layers)
- [x] Display counter of sites and images that you've selected (e.g. once you select "wildcat" you should see how many images meet those criteria and how many different sites they are at) 

ASSIGNMENTS
- [x] #257 View assignments (students)
- [x] Allow students to download their own data (falls within above issue, but really important)
- [x] #252 View assignments (teachers). 
- [x]  Delete assignments (teachers) 
- [x]  disable submit until finished & add indicator for processing 
- [x] Allow assignment descriptions to be longer. Expect more like a paragraph, that might include some guidance for students. (So teachers might essentially write instructions to their students.) 
- [x] remove pre-populated images during assignment creation. 
- [x] due date should be optional 
- [x] limit number to numeric 
- [x] **NEW** Add button for "download aggregated data" from assignment next to "download my data" from an assignment

OVERALL
- [x] Add tutorials
- [x]  #249 Create additional educational content pages. Bridget has sent content. These will be basic just like the educational resources page.

**Comment by aliburchard** [comment]
I'm editing this to remove lower priority items (I'll move them to a wish list). 

Based on internal testing, I'm going to make another list with high priority items.

**Comment by aliburchard** [comment]
okay, based on conversations just now, I'm taking "clone assignments" off the critical list.  We have one new priority item (downloading aggregated data) instead.

Ordered priorities:
1) disable submit button while thinking (let me know if this is harder than a couple hours, @simoneduca) 
2) add "download my aggregated data" button (for @simoneduca after submit button is disabled)
3) add tutorials (@shaunanoordin, after you submit your map explorer PR)
4) add bridget's extra content (whoever gets there first).

**Comment by simoneduca** [comment]
This has been completed, closing it.

**Comment by aliburchard** [comment]
WELL DONE team. I think this calls for celebrations.
