### ISSUE TITLE
Next Milestone Overview

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#278]
High Priority items based on testing updates. For after we close the Aug 5 Milestone (which we are about to do!!) 
- [x] login redirect: https://github.com/zooniverse/wildcam-gorongosa-education/issues/271. But #283. 
- [x] **update csv headers for data downloaded on assignments page** - Shaun (see #276) (PR: #286)
- [x] remove beta tag on wildcam lab link
- [x] Remove the first section of text from the landing page of the Lab where it says that this is a work in progress. 
- [x] relabel "tutorial" tab as "help"

Medium High Priority items 
- [x] update progress in real time need @marten for this 
- [x] message to students when they've finished an assignment (in Wildcam OG https://github.com/zooniverse/wildcam-gorongosa/issues/237) (PR: zooniverse/wildcam-gorongosa#245)
- [x] figure out how on earth we have the assignments as truncated by simone talk to subjects as limited in the map explorer. **Not sure this one is still relevant. I'm going to add a warning for teachers when number of images < subjects selected**
- [x] fix safari download bug (PR: #286)
- [x] editing assignments doesn't work

**Comment by shaunanoordin** [comment]
Milestone complete.
