### ISSUE TITLE
Move alpha test production - checklist

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#68]
- [x] set up a domain for alpha on production

https://learn.wildcamgorongosa.org/ has been set up.
- [x] set up deploy to production task
- [x] test login against production
- [x] test routes against production
