### ISSUE TITLE
Alpha Priorities

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#71]
**Bringing over the To-Do Priorities list from Trello so everything is in one place.** 
_Still trying to figure out the best way to roadmap and keep us on the same page with top priorities, suggestions welcome!_

Functionality Priorities
**Teachers**
- [x] Landing page for students and teachers to access portal
- [x] Teachers can log into education portal (see #26)
- [x] Teachers can create classrooms
- [x] Teachers can invite students into classrooms
- [x] Teachers can view basic stats about classrooms and students within (see #4 and #6):
  - For alpha, this is just displaying user names of students in classroom. Additional functionality listed in #74 
- [x] Teachers can click link to go to map [see Mapping Functionality Section for more]

**Students**
- [x] Students can log into education portal
- [x] Students can join classrooms based on the link/invitation sent to them (*waiting on fixed urls from @astopy)
- [x] Students have landing page once they log in (ideally displays classroom affiliation and #classifications, currently listed as beta milestones, but can move back here if that makes sense)
- [x] Students have link to classify on www.wildcamgorongosa.org 

**Mapping Functionality**
- [x] Display Map
- [x] Users can filter based on:
  - [x] species, habitat, season
  - [x] by user (me)
- [x] Export to CSV button available ( #61)
- [x] Add feedback form link (#60)

**Comment by aliburchard** [comment]
Note: I've punted the me/group/world filter to beta because we need data wiring.

**Comment by aliburchard** [comment]
YAY TO CLOSING THIS.
