### ISSUE TITLE
Beta Priorities 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#74]
_Or Alpha II, or Top Priorities, or whatever._

**Teachers**
- [x] Teachers can view basic stats about classrooms and students within (see #4 and #6)
  - [x] Classrooms Tab (see #4)
    - [x] Display # students inside classroom
    - [x] Display total # classifications made by classroom members
    - [x] Display classroom metadata (needs #51)
  - [ ] Students Tab (see #6)
    - [x] first step: just display user names (should be done with alpha)
    - [ ] display "real names"
    - [ ] display how many classifications a student has made
    - [ ] any other stats?
- [x] Teachers can add metadata for their educator account (#73)
- [x] Add tab to Educational Resources page (#82)
- [x] Add links to Wildcam FAQ and Wildcam Blog (#83)
- [x] Basic design implemented
- [x] Help Text (First step is static pages with text, can discuss tutorials later; see #84, #85) 

**Mapping Interface**
- [ ] CartoDB synced with Panoptes data to display real classifications
- [ ] Users can filter based on:
  - [ ] me/group/world (needs #95)
  - [ ]  additional filters (#72)
- [x] csv download from carto is actual csv, not json

**Comment by aliburchard** [comment]
Going to close this as these have all been done, decided against, or punted for the future.
